Repository vmware/tdnf, pull requests merged in 2023-02, with the labels that each got.

#397 backport a few fixes to 3.1
  CMakeLists.txt
  client/config.c
  client/defines.h
  client/rpmtrans.c
  common/memory.c
  common/prototypes.h
  common/utils.c
  include/tdnftypes.h
  solv/tdnfpackage.c
Labels: cla-not-required, stable-3.1

#398 Backport a few fixes to 3.3
  CMakeLists.txt
  client/config.c
  client/defines.h
  client/rpmtrans.c
  include/tdnftypes.h
  solv/tdnfpackage.c
Labels: cla-not-required, stable-3.3

#396 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-not-required

#405 Only look for packages to reinstall when we actually want to reinstall, and bump version.
  CMakeLists.txt
  client/goal.c
Labels: bug, cla-not-required, stable-3.1

#408 Only look for packages to reinstall when we actually want to reinstall
  CMakeLists.txt
  client/goal.c
  client/prototypes.h
Labels: bug, cla-not-required, stable-3.3

#401 BugFix segfault caused due to missing name param
  client/repolist.c
Labels: bug
